version: '3'
services:
  foundryvtt:
    image: grieve/fvtt-docker:latest
    container_name: fvtt
    ports: 
      - 30000:30000
    volumes:
      - /path/to/your/foundry/data/directory:/mnt/data
      - /path/to/folder/with/foundry/zip/file:/mnt/host
    restart: unless-stopped
